kind: pipeline
type: kubernetes
name: slc-camp-maps

steps:
  - name: build and push  
    image: plugins/docker
    when:
      ref:
      - refs/tags/*.*.*
    settings:
      repo: unfrl/slc-camp-maps
      username: mattunfrl
      password:
        from_secret: docker_token
      tags:
        - latest
        - "${DRONE_TAG}"
      cache_from: "unfrl/slc-camp-maps:latest"
  
  - name: deploy
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: k8s_server
      kubernetes_cert:
        from_secret: k8s_cert
      kubernetes_token:
        from_secret: k8s_token
    when:
      ref:
      - refs/tags/*.*.*
    depends_on:
    - build and push
    commands:
      - kubectl -n slc-camp-maps set image deployment/slc-camp-maps-deployment slc-camp-maps-app=unfrl/slc-camp-maps:"${DRONE_TAG}" --record